name: Django CI & Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: testrootpass
          MYSQL_DATABASE: notesdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1"
          --health-interval=10s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system libs
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev default-libmysqlclient-dev build-essential pkg-config

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mysqlclient
          pip install -r requirements.txt

      - name: Run migrations
        env:
          DB_NAME: notesdb
          DB_USER: root
          DB_PASSWORD: testrootpass
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
        run: python manage.py migrate

      - name: Run tests
        env:
          DB_NAME: notesdb
          DB_USER: root
          DB_PASSWORD: testrootpass
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
        run: python manage.py test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via Docker Compose
        run: |
          docker-compose down -v
          docker-compose up --build -d
